/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
										Includes
 *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
#include "LCD.h"
#include "Keypad.h"
#include "Seven_Segment.h"
#include "Stm32_F103C6_EXTI_Driver.h"

/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
									Generic Variables
 *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
uint8_t	IRQ_Flag = 0;

/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
									Generic Functions
 *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
void Clock_Init(void)
{
	RCC_GPIOA_CLK_EN();								/* Enable GPIO PORTA Clock*/
	RCC_GPIOB_CLK_EN();								/* Enable GPIO PORTB Clock*/
	RCC_AFIO_CLK_EN();								/* Enable AFIO Clock For EXTI */
}

static void delay_ms(uint32_t time)
{
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++);
}

void EXTI9_Callback(void)
{
	IRQ_Flag = 1;
	HAL_LCD_Write_String("IRQ EXTI9 Is Happened _|-");
	delay_ms(1000);
}


int main(void)
{
	EXTI_PinConfig_t EXTI_Cfg;										// Declare EXTI Configuration variable
	Clock_Init();																	// Initialize All Needed Clocks for GPIOA, GPIOB and AFIO
	HAL_LCD_Init();																// Initialize LCD
	HAL_LCD_Clear_Display();											// Clear LCD Screen

	EXTI_Cfg.EXTI_PIN = EXTI9PB9;									// Set GPIOB Pin 9 to EXTI Line 9
	EXTI_Cfg.Trigger_Case = EXTI_Trigger_Rising;	// Set Trigger Selection To Rising
	EXTI_Cfg.P_IRQ_Callback = EXTI9_Callback;			// Set EXTI9 IRQ handler To callback function
	EXTI_Cfg.IRQ_EN = EXTI_IRQ_Enable;						// Set EXTI IMR to Enable
	MCAL_EXTI_GPIO_Init(&EXTI_Cfg);								// Initialize EXTI9

	while(1)
	{
		if (IRQ_Flag)
		{
			HAL_LCD_Clear_Display();
			IRQ_Flag = 0;
		}
	}
}
