/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103C6_GPIO_Driver.h"
#include "stm32f103x6.h"

void Clock_Init(void)
{
	/* Enable GPIO PORTA Clock*/
	RCC_GPIOA_CLK_EN();

	/* Enable GPIO PORTB Clock*/
	RCC_GPIOB_CLK_EN();
}

void GPIO_Init(void)
{
	GPIO_PinConfig_t PinConfig;

	/* PORTA Pin 1 Floating Input: CNF1(01: Floating input) / MODE1(00: Input mode (reset state) (0100 IN CRL1)*/
	PinConfig.GPIO_PinNumber = GPIO_PIN_1;
	PinConfig.GPIO_Mode = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinConfig);

	/*PORTA Pin 13 Floating Input: CNF13(01: Floating input) / MODE13(00: Input mode (reset state) (0100 IN CRH13)*/
	PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	PinConfig.GPIO_Mode = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinConfig);


									/* === GPIO PORTB Config.=== */

	/* PORTB pin 1 PUSH-PULL OUTPUT: CNF1(00: General purpose output push-pull) / MODE1(01: Output mode, max speed 10 MHz.)(0001 in CRL1)*/
	PinConfig.GPIO_PinNumber = GPIO_PIN_1;
	PinConfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	PinConfig.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinConfig);

	/* PORTB pin 13 PUSH-PULL OUTPUT: CNF1(00: General purpose output push-pull) / MODE1(01: Output mode, max speed 10 MHz.)(0001 in CRL1)*/
	PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	PinConfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	PinConfig.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinConfig);

}

void wait_ms(uint32_t time)
{
	uint32_t i;
	for (i = 0; i < time; i++);
}

int main(void)
{
	/* Clock Init. */
	Clock_Init();

	/* GPIO Init. */
	GPIO_Init();

	while(1)
	{
		if (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_Reset)
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_Reset);
		}

		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == GPIO_PIN_Set)
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		}
		wait_ms(1000);
	}
}
