/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

typedef volatile unsigned int  vuint32;

/* RCC Registers */
#define RCC_BASE       0x40021000
#define RCC_APB2ENR    *(vuint32 *)(RCC_BASE + 0x18)

/* GPIO PORTA Registers*/
#define GPIOA_BASE     0x40010800
#define GPIOA_CRL      *(vuint32 *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH      *(vuint32 *)(GPIOA_BASE + 0x04)
#define GPIOA_IDR      *(vuint32 *)(GPIOA_BASE + 0x08)

/* GPIO PORTB Registers*/
#define GPIOB_BASE     0x40010C00
#define GPIOB_CRL      *(vuint32 *)(GPIOB_BASE + 0x00)
#define GPIOB_CRH      *(vuint32 *)(GPIOB_BASE + 0x04)
#define GPIOB_ODR      *(vuint32 *)(GPIOB_BASE + 0x0C)


void Clock_Init(void)
{
	/* Enable GPIO PORTA Clock*/
	RCC_APB2ENR |= (1 << 2);

	/* Enable GPIO PORTA Clock*/
	RCC_APB2ENR |= (1 << 3);
}

void GPIO_Init(void)
{
									/* === GPIO PORTA Config.=== */
	/* RESET GPIOX To ZERO*/
	GPIOA_CRL = 0x0;
	GPIOA_CRH = 0x0;

	/* PORTA Pin 1 Floating Input: CNF1(01: Floating input) / MODE1(00: Input mode (reset state) (0100 IN CRL1)*/
	GPIOA_CRL |= (1 << 6);

	/*PORTA Pin 13 Floating Input: CNF13(01: Floating input) / MODE13(00: Input mode (reset state) (0100 IN CRH13)*/
	GPIOA_CRH |= (1 << 22);

									/* === GPIO PORTB Config.=== */

	/* PORTB pin 1 PUSH-PULL OUTPUT: CNF1(00: General purpose output push-pull) / MODE1(01: Output mode, max speed 10 MHz.)(0001 in CRL1)*/
	GPIOB_CRL &= ~(0b1111 << 4);                 // reset CNF and MODE of Pin 1
	GPIOB_CRL |= (1 << 4);                       // Put 1 in MODE bit 4

	/* PORTB pin 1 PUSH-PULL OUTPUT: CNF1(00: General purpose output push-pull) / MODE1(01: Output mode, max speed 10 MHz.)(0001 in CRL1)*/
	GPIOB_CRH &= ~(0b1111 << 20);                 // reset CNF and MODE of Pin 13
	GPIOB_CRH |= (1 << 20);                        // Put 1 in MODE bit 20
}

void wait_ms(uint32_t time)
{
	uint32_t i;
	for (i = 0; i < time; i++);
}

int main(void)
{
	/* Clock Init. */
	Clock_Init();

	/* GPIO Init. */
	GPIO_Init();

	while(1)
	{
		if (((GPIOA_IDR & (1 << 1)) >> 1) == 0)
		{
			GPIOB_ODR ^= 1 << 1;
			while(((GPIOA_IDR & (1 << 1)) >> 1) == 0);
		}

		if(((GPIOA_IDR & (1 << 13)) >> 13) == 1)
		{
			GPIOB_ODR ^= 1 << 13;
		}
		wait_ms(1000);
	}
}
