/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "LCD.h"
#include "Keypad.h"
#include "Seven_Segment.h"

void Clock_Init(void)
{
	RCC_GPIOA_CLK_EN();								/* Enable GPIO PORTA Clock*/
	RCC_GPIOB_CLK_EN();								/* Enable GPIO PORTB Clock*/
}

static void delay_ms(uint32_t time)
{
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++);
}

int main(void)
{
	unsigned char numbers[] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0'};
	uint8_t Segment_Numbers[] = {Zero, One, Two, Three, Four, Five, Six, Seven, Eight, Nine, Zero};
	unsigned char Key_Pressed;
	Clock_Init();									// Clock Init
	HAL_LCD_Init();									// LCD Init
	HAL_LCD_Write_String("HEY!!");					// Send HEY
	HAL_LCD_GoTo_XY(2, 2);
	HAL_LCD_Write_String("This Is Mina!");
	HAL_Seven_Segment_Init();
	delay_ms(50);									// wait a 50 Sec
	HAL_LCD_Clear_Display();						// Clear Display

	for (int i = 0; i < 11; i++)
	{
		HAL_LCD_Write_Character(numbers[i]);
		HAL_Seven_Segment_Send(Segment_Numbers[i]);
		delay_ms(100);
	}
	HAL_Keypad_Init();								// Keypad Init
	delay_ms(50);									// wait a 50 Sec
	HAL_LCD_Clear_Display();						// Clear Display
	HAL_LCD_Write_String("Keypad Is Ready");		// Send Keypad Is Ready
	delay_ms(50);									// wait a 50 Sec
	HAL_LCD_Clear_Display();						// Clear Display

	while(1)
	{
		Key_Pressed = HAL_Keypad_Getkey();

		switch (Key_Pressed) {
			case 'A':
				break;

			default:
				HAL_LCD_Write_Character(Key_Pressed);
				break;
		}
	}
}
